language: objective-c
cache:
    directories:
    - $HOME/.ccache
install:
- gem install xcpretty
- brew install ccache
- PATH=$PATH:/usr/local/opt/ccache/libexec
script:
- set -o pipefail && xcodebuild -project "GoogleMock.xcodeproj" -scheme "GoogleMock" build analyze test | xcpretty
before_script:
- ccache -s
- ccache -z
after_script:
- ccache -s
notifications:
    slack: xs-labs:FXh1yLXNkpcVxKZhZU6icdhI
